---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: CloudByteSolutions/testing
      ephemeral: true
      env: []